### ISSUE TITLE
HM-CC-RT-DN with HM-TC-IT-WM-W-EU link parameters setting problem

### ISSUE THREAD

**Issue by soosp** [Homegear/Homegear#311]
Hi,

I have HM-CC-RT-DN's linked with an HM-TC-IT-WM-W-EU. The channel 2 (THERMALCONTROL_TRANSMIT) of HM-TC-IT-WM-W-EU linked with channel 2 (CLIMATECONTROL_RECEIVER) of the HM-CC-RT-DN. I configured the links in the Homematic manager with success. But if I want to configure the link parameters I got the following error message window in Homematic manager twice:
```
BidCosRF-getParamset
{"code":-2,"faultCode":-2,"faultString":"Unknown channel."}
```
After that got a new error window:
```
formLinkParamset paramset missing
Please try again.
```
In HomeMatic Konfigurator I got the following error message:
```
An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root).
```

All other type of links I have can be configured but this ones are could'n.

Homegear version is 0.7.39-2768 installed from the Raspbian Stretch repository.

**Comment by soosp** [comment]
It is not so mutch even if we are on LogLevel 4:
```
03/29/19 06:48:57.643 RPC Server (Port 2001): Info: Connection from ::ffff:192.168.14.248:50535 accepted. Client number: 90
03/29/19 06:48:57.644 RPC Server (Port 2001): Info: RPC server client id for client number 90 is: 10
03/29/19 06:48:57.646 RPC Server (Port 2001): Info: Client number 90 is calling RPC method: getLinkInfo (1) Parameters:
(String) OEQ0849549:2
(String) OEQ2424267:2
03/29/19 06:48:57.672 RPC Server (Port 2001): Info: Connection from ::ffff:192.168.14.248:50536 accepted. Client number: 91
03/29/19 06:48:57.673 RPC Server (Port 2001): Info: RPC server client id for client number 91 is: 11
03/29/19 06:48:57.675 RPC Server (Port 2001): Info: Client number 91 is calling RPC method: getParamset (1) Parameters:
(String) OEQ0849549:2
(String) OEQ2424267:2
03/29/19 06:48:58.637 RPC Server (Port 2001): Info: Connection from ::ffff:192.168.14.248:50537 accepted. Client number: 92
03/29/19 06:48:58.638 RPC Server (Port 2001): Info: RPC server client id for client number 92 is: 12
03/29/19 06:48:58.640 RPC Server (Port 2001): Info: Client number 92 is calling RPC method: getParamset (1) Parameters:
(String) OEQ2424267:2
(String) OEQ0849549:2

```

**Comment by soosp** [comment]
Here is a log fragment at LogLevel 5:
```
Content-Length: 446
Connection: close

<?xml version="1.0"?>
<methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value>event</value></member><member><name>params</name><value><array><data><value>hmm_BidCos-RF</value><value>OEQ0849548:7</value><value>DECISION_VALUE</value><value><i4>0</i4></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>

03/29/19 07:00:13.186 RPC client: Debug: Packet received: 485454502F312E3120323030204F4B0D0A436F6E74656E742D547970653A20746578742F786D6C0D0A436F6E74656E742D4C656E6774683A203136310D0A446174653A204672692C203239204D617220323031392030363A30303A313320474D540D0A436F6E6E656374696F6E3A20636C6F73650D0A0D0A3C3F786D6C2076657273696F6E3D22312E30223F3E3C6D6574686F64526573706F6E73653E3C706172616D733E3C706172616D3E3C76616C75653E3C61727261793E3C646174613E3C76616C75653E3C737472696E673E3C2F737472696E673E3C2F76616C75653E3C2F646174613E3C2F61727261793E3C2F76616C75653E3C2F706172616D3E3C2F706172616D733E3C2F6D6574686F64526573706F6E73653E
03/29/19 07:00:13.191 RPC client: Debug: Received packet from server 192.168.44.248:
<?xml version="1.0"?><methodResponse><params><param><value><array><data><value><string></string></value></data></array></value></param></params></methodResponse>^@
03/29/19 07:00:13.192 RPC client: Response was:
(Array length=1)
[
  (String)
]
03/29/19 07:00:21.072 UPnP Server: Debug: Sending notify packets.
03/29/19 07:00:21.664 RPC Server (Port 2001): Debug: Joining read thread of client 6
03/29/19 07:00:21.664 RPC Server (Port 2001): Debug: Client 6 removed.
03/29/19 07:00:21.664 RPC Server (Port 2001): Debug: Joining read thread of client 7
03/29/19 07:00:21.664 RPC Server (Port 2001): Debug: Client 7 removed.
03/29/19 07:00:21.664 RPC Server (Port 2001): Debug: Joining read thread of client 8
03/29/19 07:00:21.664 RPC Server (Port 2001): Debug: Client 8 removed.
03/29/19 07:00:23.756 RPC Server (Port 2001): Info: Connection from ::ffff:192.168.44.248:53605 accepted. Client number: 58
03/29/19 07:00:23.757 RPC Server (Port 2001): Info: RPC server client id for client number 58 is: 9
03/29/19 07:00:23.758 RPC Server (Port 2001): Listening for incoming packets from client number 58.
03/29/19 07:00:23.759 RPC Server (Port 2001): Debug: Packet received: 504F5354202F20485454502F312E310D0A557365722D4167656E743A204E6F64654A5320584D4C2D52504320436C69656E740D0A436F6E74656E742D547970653A20746578742F786D6C0D0A4163636570743A20746578742F786D6C0D0A4163636570742D436861727365743A20555446380D0A436F6E6E656374696F6E3A204B6565702D416C6976650D0A436F6E74656E742D4C656E6774683A203231370D0A486F73743A203139322E3136382E34342E3130313A323030310D0A0D0A3C3F786D6C2076657273696F6E3D22312E30223F3E3C6D6574686F6443616C6C3E3C6D6574686F644E616D653E6765744C696E6B496E666F3C2F6D6574686F644E616D653E3C706172616D733E3C706172616D3E3C76616C75653E3C737472696E673E4F4551303835303638333A323C2F737472696E673E3C2F76616C75653E3C2F706172616D3E3C706172616D3E3C76616C75653E3C737472696E673E4F4551323431363235313A323C2F737472696E673E3C2F76616C75653E3C2F706172616D3E3C2F706172616D733E3C2F6D6574686F6443616C6C3E
03/29/19 07:00:23.759 RPC Server (Port 2001): Info: Client number 58 is calling RPC method: getLinkInfo (1) Parameters:
(String) OEQ0850683:2
(String) OEQ2416251:2
03/29/19 07:00:23.760 RPC Server (Port 2001): Response:
(Struct length=2)
{
  [DESCRIPTION] (String) StandardverknĂĽpfung Wandthermostat (Sender) - EmpfĂ¤nger f. Soll-/Ist-Temperatur
  [NAME] (String) Spare room thermostat mit Spare room radiator thermostat - right
}
03/29/19 07:00:23.760 RPC Server (Port 2001): Response packet: HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: text/xml
Content-Length: 375

<?xml version="1.0"?><methodResponse><params><param><value><struct><member><name>DESCRIPTION</name><value>StandardverknĂĽpfung Wandthermostat (Sender) - EmpfĂ¤nger f. Soll-/Ist-Temperatur </value></member><member><name>NAME</name><value>Spare room thermostat mit Spare room radiator thermostat - right</value></member></struct></value></param></params></methodResponse>

03/29/19 07:00:23.784 RPC Server (Port 2001): Debug: Connection to client number 58 closed (3).
03/29/19 07:00:23.786 RPC Server (Port 2001): Info: Connection from ::ffff:192.168.44.248:53606 accepted. Client number: 59
03/29/19 07:00:23.786 RPC Server (Port 2001): Info: RPC server client id for client number 59 is: 10
03/29/19 07:00:23.787 RPC Server (Port 2001): Listening for incoming packets from client number 59.
03/29/19 07:00:23.788 RPC Server (Port 2001): Debug: Packet received: 504F5354202F20485454502F312E310D0A557365722D4167656E743A204E6F64654A5320584D4C2D52504320436C69656E740D0A436F6E74656E742D547970653A20746578742F786D6C0D0A4163636570743A20746578742F786D6C0D0A4163636570742D436861727365743A20555446380D0A436F6E6E656374696F6E3A204B6565702D416C6976650D0A436F6E74656E742D4C656E6774683A203231370D0A486F73743A203139322E3136382E34342E3130313A323030310D0A0D0A3C3F786D6C2076657273696F6E3D22312E30223F3E3C6D6574686F6443616C6C3E3C6D6574686F644E616D653E676574506172616D7365743C2F6D6574686F644E616D653E3C706172616D733E3C706172616D3E3C76616C75653E3C737472696E673E4F4551303835303638333A323C2F737472696E673E3C2F76616C75653E3C2F706172616D3E3C706172616D3E3C76616C75653E3C737472696E673E4F4551323431363235313A323C2F737472696E673E3C2F76616C75653E3C2F706172616D3E3C2F706172616D733E3C2F6D6574686F6443616C6C3E
03/29/19 07:00:23.788 RPC Server (Port 2001): Info: Client number 59 is calling RPC method: getParamset (1) Parameters:
(String) OEQ0850683:2
(String) OEQ2416251:2
03/29/19 07:00:23.789 RPC Server (Port 2001): Response:
(Struct length=2)
{
  [faultCode] (Integer) -2
  [faultString] (String) Unknown channel.
}
03/29/19 07:00:23.789 RPC Server (Port 2001): Response packet: HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: text/xml
Content-Length: 240

<?xml version="1.0"?><methodResponse><fault><value><struct><member><name>faultCode</name><value><i4>-2</i4></value></member><member><name>faultString</name><value>Unknown channel.</value></member></struct></value></fault></methodResponse>

03/29/19 07:00:23.813 RPC Server (Port 2001): Debug: Connection to client number 59 closed (3).
03/29/19 07:00:25.126 RPC Server (Port 2001): Info: Connection from ::ffff:192.168.44.248:53607 accepted. Client number: 60
03/29/19 07:00:25.126 RPC Server (Port 2001): Info: RPC server client id for client number 60 is: 11
03/29/19 07:00:25.132 RPC Server (Port 2001): Listening for incoming packets from client number 60.
03/29/19 07:00:25.132 RPC Server (Port 2001): Debug: Packet received: 504F5354202F20485454502F312E310D0A557365722D4167656E743A204E6F64654A5320584D4C2D52504320436C69656E740D0A436F6E74656E742D547970653A20746578742F786D6C0D0A4163636570743A20746578742F786D6C0D0A4163636570742D436861727365743A20555446380D0A436F6E6E656374696F6E3A204B6565702D416C6976650D0A436F6E74656E742D4C656E6774683A203231370D0A486F73743A203139322E3136382E34342E3130313A323030310D0A0D0A3C3F786D6C2076657273696F6E3D22312E30223F3E3C6D6574686F6443616C6C3E3C6D6574686F644E616D653E676574506172616D7365743C2F6D6574686F644E616D653E3C706172616D733E3C706172616D3E3C76616C75653E3C737472696E673E4F4551323431363235313A323C2F737472696E673E3C2F76616C75653E3C2F706172616D3E3C706172616D3E3C76616C75653E3C737472696E673E4F4551303835303638333A323C2F737472696E673E3C2F76616C75653E3C2F706172616D3E3C2F706172616D733E3C2F6D6574686F6443616C6C3E
03/29/19 07:00:25.133 RPC Server (Port 2001): Info: Client number 60 is calling RPC method: getParamset (1) Parameters:
(String) OEQ2416251:2
(String) OEQ0850683:2
03/29/19 07:00:25.133 RPC Server (Port 2001): Response:
(Struct length=2)
{
  [faultCode] (Integer) -2
  [faultString] (String) Unknown channel.
}
03/29/19 07:00:25.133 RPC Server (Port 2001): Response packet: HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: text/xml
Content-Length: 240

<?xml version="1.0"?><methodResponse><fault><value><struct><member><name>faultCode</name><value><i4>-2</i4></value></member><member><name>faultString</name><value>Unknown channel.</value></member></struct></value></fault></methodResponse>

03/29/19 07:00:25.157 RPC Server (Port 2001): Debug: Connection to client number 60 closed (3).

```

**Comment by lfrancke** [comment]
I have the same issue. @soosp Did you ever find out what's going on here?

**Comment by hfedcba** [comment]
@lfrancke: Which Homegear version do you have installed? 0.7.47-3316?

**Comment by lfrancke** [comment]
No, unfortunately not. It's 0.7.45-3101
Shame on me for not checking this earlier.
That said: The latest release on Github seems to be 0.7.40 and the changelog ends 2017...
I see 0.7.47 mentioned on the Downloads page but the apt repository for buster on raspian lists 0.7.45 as the last version.

Is there something in .46 or .47 that could fix this?

**Comment by hfedcba** [comment]
There is an error that prevents compilation for Raspbian Buster at the moment. It might already be fixed - we are just testing. You could test the current nightly or wait a few days, then 0.7.47 should be online for Raspbian Buster as well. Before I look into the code we should definitely check if the error is still there with the current version.

**Comment by hfedcba** [comment]
I just checked - Raspbian Stable 0.7.47 should be online tomorrow late evening.

**Comment by lfrancke** [comment]
Great, thank you for the update. I'll check when I'm back home on the weekend.

**Comment by lfrancke** [comment]
I updated and it updated directly to 0.8 but the same error still exists.
Happy to provide any information that could help but (for me at least) this is not a critical issue.

**Comment by hfedcba** [comment]
Sorry for the late reply... To rule out, if it is a Homegear problem, could you try if it works with https://ref.homegear.eu/rpc.html#putParamset from the console?

    homegear -e rc '$hg->putParamset(...);'

**Comment by lhurt** [comment]
Just hit the same issue. Any progress or solution since the last comment? It's 10 months now.
Thanks for updating.

**Comment by hfedcba** [comment]
No, there is no progress. The problem probably is easy to fix. Could you check if `homegear -e rc '$hg->getParamset("OEQ2416251:2", "OEQ2424267:2");'` works from the console (replace the serial numbers with yours)? That info would really help.

**Comment by lhurt** [comment]
> No, there is no progress. The problem probably is easy to fix. Could you check if `homegear -e rc '$hg->getParamset("OEQ2416251:2", "OEQ2424267:2");'` works from the console (replace the serial numbers with yours)? That info would really help.

It throws an error.
```
docker exec -ti homegear homegear -e rc '$hg->getParamset("REQ0835925:2", "NEQ1489604:2");'
PHP Fatal error:  Uncaught Homegear\HomegearException: Unknown channel. in /var/lib/homegear/scripts/inline.php:7
Stack trace:
#0 /var/lib/homegear/scripts/inline.php(7): Homegear\Homegear->__call('getParamset', Array)
#1 {main}
  thrown in /var/lib/homegear/scripts/inline.php on line 7
```

**Comment by hfedcba** [comment]
Could you determine the IDs of the two devices (= peers) and execute the command again using:

`docker exec -ti homegear homegear -e rc '$hg->getParamset(<HM-TC-IT-WM-W-EU peer ID>, 2, <HM-CC-RT-DN peer ID>, 2);'`?

**Comment by lhurt** [comment]
> Could you determine the IDs of the two devices (= peers) and execute the command again using:
> 
> `docker exec -ti homegear homegear -e rc '$hg->getParamset(<HM-TC-IT-WM-W-EU peer ID>, 2, <HM-CC-RT-DN peer ID>, 2);'`?

Unfortunately an error again
```
docker exec -ti homegear homegear -e rc '$hg->getParamset(39, 2, 38, 2);'
PHP Fatal error:  Uncaught Homegear\HomegearException: Unknown channel. in /var/lib/homegear/scripts/inline.php:7
Stack trace:
#0 /var/lib/homegear/scripts/inline.php(7): Homegear\Homegear->__call('getParamset', Array)
#1 {main}
  thrown in /var/lib/homegear/scripts/inline.php on line 7
```
Do you have an idea why this is happening?

**Comment by hfedcba** [comment]
> Do you have an idea why this is happening?

No, not yet... But we are getting close. Could you execute:

`docker exec -ti homegear homegear -e rc 'print_v($hg->getParamset(39));'`

and

`docker exec -ti homegear homegear -e rc 'print_v($hg->getParamset(38));'`?

**Comment by lhurt** [comment]
> > Do you have an idea why this is happening?
> 
> No, not yet... But we are getting close. Could you execute:
> 
> `docker exec -ti homegear homegear -e rc 'print_v($hg->getParamset(39));'`
> 
> and
> 
> `docker exec -ti homegear homegear -e rc 'print_v($hg->getParamset(38));'`?

They throw identical errors
```
docker exec -ti homegear homegear -e rc 'print_v($hg->getParamset(39));'
PHP Fatal error:  Uncaught Homegear\HomegearException: Wrong parameter count. in /var/lib/homegear/scripts/inline.php:7
Stack trace:
#0 /var/lib/homegear/scripts/inline.php(7): Homegear\Homegear->__call('getParamset', Array)
#1 {main}
  thrown in /var/lib/homegear/scripts/inline.php on line 7
```

**Comment by hfedcba** [comment]
Ah, my mistake, I did not replace the method name... I meant

´docker exec -ti homegear homegear -e rc 'print_v($hg->getLinks(39));'`

and

`docker exec -ti homegear homegear -e rc 'print_v($hg->getLinks(38));'`?

**Comment by lhurt** [comment]
> Ah, my mistake, I did not replace the method name... I meant
> 
> `docker exec -ti homegear homegear -e rc 'print_v($hg->getLinks(39));'`
> 
> and
> 
> `docker exec -ti homegear homegear -e rc 'print_v($hg->getLinks(38));'`?

That actually produced some output.

```
docker exec -ti homegear homegear -e rc 'print_v($hg->getLinks(38));'
(Array length=2)
[
  (Struct length=9)
  {
    [DESCRIPTION] (String) 
    [FLAGS] (Integer) 0
    [NAME] (String) 
    [RECEIVER] (String) NEQ1489604:2
    [RECEIVER_CHANNEL] (Integer) 2
    [RECEIVER_ID] (Integer) 38
    [SENDER] (String) REQ0835925:2
    [SENDER_CHANNEL] (Integer) 2
    [SENDER_ID] (Integer) 39
  }
  (Struct length=9)
  {
    [DESCRIPTION] (String) 
    [FLAGS] (Integer) 0
    [NAME] (String) 
    [RECEIVER] (String) NEQ1489604:3
    [RECEIVER_CHANNEL] (Integer) 3
    [RECEIVER_ID] (Integer) 38
    [SENDER] (String) OEQ0221247:1
    [SENDER_CHANNEL] (Integer) 1
    [SENDER_ID] (Integer) 37
  }
]
```
and
```
docker exec -ti homegear homegear -e rc 'print_v($hg->getLinks(39));'
(Array length=2)
[
  (Struct length=9)
  {
    [DESCRIPTION] (String) 
    [FLAGS] (Integer) 0
    [NAME] (String) 
    [RECEIVER] (String) NEQ1489604:2
    [RECEIVER_CHANNEL] (Integer) 2
    [RECEIVER_ID] (Integer) 38
    [SENDER] (String) REQ0835925:2
    [SENDER_CHANNEL] (Integer) 2
    [SENDER_ID] (Integer) 39
  }
  (Struct length=9)
  {
    [DESCRIPTION] (String) 
    [FLAGS] (Integer) 0
    [NAME] (String) 
    [RECEIVER] (String) REQ0835925:3
    [RECEIVER_CHANNEL] (Integer) 3
    [RECEIVER_ID] (Integer) 39
    [SENDER] (String) OEQ0221247:1
    [SENDER_CHANNEL] (Integer) 1
    [SENDER_ID] (Integer) 37
  }
]
```
Did it help to track the problem?

**Comment by hfedcba** [comment]
Yes, that should help. Thank you so much. This means that the link is known to Homegear correctly. I'll look at it tomorrow.

**Comment by lhurt** [comment]
> Yes, that should help. Thank you so much. This means that the link is known to Homegear correctly. I'll look at it tomorrow.

You are most welcome. Actually I have no operation issues, but the error shouldn't show up anyways.

**Comment by hfedcba** [comment]
Does this work?

`docker exec -ti homegear homegear -e rc '$hg->getParamset(37, 1, 38, 3);'`?

The issue actually might not be an error...

**Comment by lhurt** [comment]
> Does this work?
> 
> `docker exec -ti homegear homegear -e rc '$hg->getParamset(37, 1, 38, 3);'`?
> 
> The issue actually might not be an error...

Depends on what you expect.
```
pi@automation:~ $ docker exec -ti homegear homegear -e rc '$hg->getParamset(37, 1, 38, 3);'
pi@automation:~ $ 
```

**Comment by hfedcba** [comment]
Oh, I forgot the `print_v`, so there is no output:

docker exec -ti homegear homegear -e rc 'print_v($hg->getParamset(37, 1, 38, 3));'

**Comment by lhurt** [comment]
> Oh, I forgot the `print_v`, so there is no output:
> 
> `docker exec -ti homegear homegear -e rc 'print_v($hg->getParamset(37, 1, 38, 3));'`

That one gives me this output
```
docker exec -ti homegear homegear -e rc 'print_v($hg->getParamset(37, 1, 38, 3));'
(Struct length=2)
{
  [EXPECT_AES] (Boolean) 0
  [PEER_NEEDS_BURST] (Boolean) 1
}
```

Is it helpful?

**Comment by hfedcba** [comment]
> Is it helpful?

Yes, this means, that link parameter sets are working as expected and there is no error at all. Channel 2 just does not have a link parameter set, so there is nothing to configure (see https://ref.homegear.eu/device.html?directory=HomeMatic+BidCoS&file=rf_cc_rt_dn.xml&familyLink=homematicbidcos&name=HM-CC-RT-DN#affixSection2). Channel 3 does have a link parameter set, that is why there is an output and no error message.

I improved the error message now, though. See https://github.com/Homegear/libhomegear-base/commit/7f474037b22651a76b7cf5f6e1360f502b0cc7c4.

I'm closing this issue now.

Again thank you so much for testing this with me.

**Comment by lhurt** [comment]
You're welcome. I'm happy to help.
